### ISSUE TITLE
建议加个搜索功能

### ISSUE THREAD

**Issue by q1187455065** [xfmujie/musicBox#1]
很感谢作者开源的这款软件，这个软件真的很好用，不过搜索功能要是能加个像百度搜索提示就更好了，下面的代码是我生成的，稍微改了下，希望作者添加类型的功能，谢谢！
`if (typeof openSug === "function" && document.getElementById("search_box") != null) openSug( "search_box", {
  	// Background color of the prompt box.
	bgcolor : "#e1ffe5",
	
	// Highlighted background color of the prompt box.
	bgcolorHI : "#cae5d1dd",
	
	// Border color of the prompt box.
	borderColor : "",
	
	// Color of the text in the prompt box.
	fontColor : "",
	
	// Highlight the text color in the prompt box.
	fontColorHI : "#b10dc9",
	
	// Font of the text in the prompt box.
	fontFamily : "Montserrat,sans-serif",
	
	// Text font size in the prompt box.
	fontSize : "14px",
	
	// Inner margin of the prompt box
	padding : "6px 25px",
	
	// The circular corner radius of the border.
	radius : "20px",
	
	// The shadow effect of the border.
	shadow : "rgb(0 0 0 / 50%) 0px 6px 10px",
	
	// Search for the data source of the prompt box.
	source : "kugou",
	
	// Whether the form is automatically submitted when selecting the prompts.
	sugSubmit : true,
	
	// The width of the prompt box.
	// Recommended null value.
	width : "",
	
	// The lateral offset of the prompt box relative to the input box.
	// Negative values are shifted to the right
	XOffset : "",
	
	// The longitudinal offset of the prompt box relative to the input box.
	// Negative values are offset downward
	YOffset : "-4"
}, function (){
});`

**Comment by xfmujie** [comment]
感谢你的建议，但前面的开发进程还没完成，且搜索建议对我来说还有些困难，比如数据源还有消抖问题等等，所以得之后再考虑加上搜索建议

**Comment by q1187455065** [comment]
> 感谢你的建议，但前面的开发进程还没完成，且搜索建议对我来说还有些困难，比如数据源还有消抖问题等等，所以得之后再考虑加上搜索建议

网上可以生成脚本代码
![Preview](https://user-images.githubusercontent.com/113352962/232089371-7cd97264-f773-4fb1-81da-83fd051f7d56.png)
![Preview-1](https://user-images.githubusercontent.com/113352962/232089378-a57a8d45-d30d-4e3c-8585-266e8cf31621.png)

**Comment by xfmujie** [comment]
牛啊，不但直接生成还可以直接发送请求？大佬细说，怎么实现的

**Comment by q1187455065** [comment]
> 牛啊，不但直接生成还可以直接发送请求？大佬细说，怎么实现的

直接生成，然后自己调下位置就行了
这是我修改后的代码
![preview](https://user-images.githubusercontent.com/113352962/232097463-a20e29a8-9bb6-444e-a319-2914a0be8cd1.png)

**Comment by xfmujie** [comment]
谢谢大佬！已经非常顺利地添加上了(≧∇≦)ﾉ
