### ISSUE TITLE
解析vip歌曲又回来了

### ISSUE THREAD

**Issue by chorblack** [xfmujie/musicBox#5]
[kw.zip](https://github.com/xfmujie/musicBox/files/12107373/kw.zip)
这个之前有大佬写的根据加密算法得到App协议的直链接
musicBox我用着挺不错的，希望可以复活
![d4030b79bb2f27b675fe55251bafdfd3](https://github.com/xfmujie/musicBox/assets/67499253/4a8b1dfb-1329-481e-8f69-971bb9131246)

**Comment by chorblack** [comment]
issue先关了

**Comment by chorblack** [comment]
![image](https://github.com/xfmujie/musicBox/assets/67499253/a8856062-2d2c-4461-92f3-10174d33642a)

**Comment by xfmujie** [comment]
今天我也看了一眼那个项目的issue，感觉有机会，但是我这边台风过了几天却一直没来电，来电了第一时间研究研究

**Comment by zhaoyuqiqi** [comment]
现在这个好像已经失效了

**Comment by xfmujie** [comment]
> 现在这个好像已经失效了

是的，貌似换算法了，不懂爬虫扣算法，音乐盒可能要被荒废了😢

**Comment by xfmujie** [comment]
f'http://mobi.kuwo.cn/mobi.s?f=kuwo&q={KwApi.base64_encrypt(KwApi,f"user=0&android_id=0&prod=kwplayer_ar_8.5.5.0&corp=kuwo&newver=3&vipver=8.5.5.0&source=kwplayer_ar_8.5.5.0_apk_keluze.apk&p2p=1&notrace=0&type=convert_url2&br=320kmp3&format=flac|mp3|aac&sig=0&rid={rid}&priority=bitrate&loginUid=0&network=WIFI&loginSid=0&mode=download")}'

**Comment by zhaoyuqiqi** [comment]
python脚本还是用的这个压缩包吗

**Comment by xfmujie** [comment]
> python脚本还是用的这个压缩包吗

是的

**Comment by zhaoyuqiqi** [comment]
我这边用脚本跑出来链接好像不太对 直接404了  哈哈哈哈哈哈 或许是我传错参数了吧   明天再看看  谢谢楼主

**Comment by xfmujie** [comment]
> 我这边用脚本跑出来链接好像不太对 直接404了 哈哈哈哈哈哈 或许是我传错参数了吧 明天再看看 谢谢楼主

我本机请求也是404，不知道什么情况😂但是云端请求却是正常的

**Comment by zhaoyuqiqi** [comment]
靠  想起来了  得加请求头  我本地没加请求头 所以被server拒绝了  多谢楼主提醒本地404    我还以为算法错了

**Comment by zhaoyuqiqi** [comment]
现在的python的脚本真黄了，应该是加密算法换了
