### ISSUE TITLE
安卓基于chrome的浏览器好像无法播放音乐

### ISSUE THREAD

**Issue by twamix** [xfmujie/musicBox#6]
比如kiwi等

**Comment by xfmujie** [comment]
是的，由于酷我音源不支持https，而chrome的安全策略中是不允许https网页上出现http资源的，PC端可以用户设定，但是移动端chrome并没有给出相关设置，所以无解，安卓可以使用chrome内核之外的浏览器

**Comment by gdf159159** [comment]
> 是的，由于酷我音源不支持https，而chrome的安全策略中是不允许https网页上出现http资源的，PC端可以用户设定，但是移动端chrome并没有给出相关设置，所以无解，安卓可以使用chrome内核之外的浏览器

其实你只要把获取的网址 替换成http就可以网页播放了 根本不用改设置

**Comment by gdf159159** [comment]
> 是的，由于酷我音源不支持https，而chrome的安全策略中是不允许https网页上出现http资源的，PC端可以用户设定，但是移动端chrome并没有给出相关设置，所以无解，安卓可以使用chrome内核之外的浏览器

还有 fcapp.run  这个服务器是谁的  页面标头不限制输出json 我这测试ios上的浏览器不好使

**Comment by xfmujie** [comment]
> > 是的，由于酷我音源不支持https，而chrome的安全策略中是不允许https网页上出现http资源的，PC端可以用户设定，但是移动端chrome并没有给出相关设置，所以无解，安卓可以使用chrome内核之外的浏览器
> 
> 其实你只要把获取的网址 替换成http就可以网页播放了 根本不用改设置

原始获取到的链接就是http的，划重点，安全策略不允许https网页上出现http资源🤔浏览器会自动将其转成https来发送请求，所以只能由用户来干预浏览器，更改设置项了

**Comment by xfmujie** [comment]
> > 是的，由于酷我音源不支持https，而chrome的安全策略中是不允许https网页上出现http资源的，PC端可以用户设定，但是移动端chrome并没有给出相关设置，所以无解，安卓可以使用chrome内核之外的浏览器
> 
> 还有 fcapp.run 这个服务器是谁的 页面标头不限制输出json 我这测试ios上的浏览器不好使
> 
> 不能搜索等操作

这是阿里云自动分配的域名，浏览器访问会自动当附件下载，接口调试可以用调试工具postcat、apifox之类的

**Comment by gdf159159** [comment]
> > > 是的，由于酷我音源不支持https，而chrome的安全策略中是不允许https网页上出现http资源的，PC端可以用户设定，但是移动端chrome并没有给出相关设置，所以无解，安卓可以使用chrome内核之外的浏览器
> > 
> > 
> > 其实你只要把获取的网址 替换成http就可以网页播放了 根本不用改设置
> 
> 原始获取到的链接就是http的，划重点，安全策略不允许https网页上出现http资源🤔浏览器会自动将其转成https来发送请求，所以只能由用户来干预浏览器，更改设置项了

是我的问题   我忘了改过什么了 我的edge  https页面下可以加载http资源

ios的问题是list.js 11行 window.parent   要关闭阻止跨网站跟踪 或者干脆删掉

终于可以用了 感谢大佬

**Comment by xfmujie** [comment]
issue关了哈( •̀ ω •́ )✧
